Move secrets
Infisical/infisical pull request #1081
Opened 2023-10-12 01:22 UTC by EBEN4REAL

# Description 📣
This feature enables users perform bulk actions on secrets such as deleting multiple secrets and moving secrets into a different folder

## Type ✨

- [ ] Bug fix
- [x] New feature
- [ ] Breaking change
- [ ] Documentation

# Tests 🛠️

<img width="768" alt="image" src="https://github.com/Infisical/infisical/assets/23234918/81b25725-224e-42b0-bfbe-84237ffb0c32">

[Feature Demo](https://share.vidyard.com/watch/WS18ETEHJykhsCVMxo7DDD?)

- [x] I have read the [contributing guide](https://infisical.com/docs/contributing/overview), agreed and acknowledged the [code of conduct](https://infisical.com/docs/contributing/code-of-conduct). 📝

2023-10-20 10:21 UTC, maidul98 commented
Looks cool! I have requested @akhilmhdh  to look into this since he works closely with the frontend

2023-10-20 14:18 UTC, EBEN4REAL commented
Alright

2023-10-20 17:04 UTC, akhilmhdh requested changes
Need to refactor to remove usage of folder id, bring back permission check and also please lint the code especially front-end

2023-10-20 17:04 UTC, akhilmhdh commented on frontend/src/views/SecretMainPage/components/ActionBar/ActionBar.tsx
> +        <div className={twMerge("fixed transform  flex justify-center opacity-0 bottom-[20px] left-[220px] scale-50 right-0 z-10 pointer-events-none translate-y-20  transition-all duration-300", Obje
multiple comments over this one

1. Missing permission check 
2. Avoid defining custom tailwind classes which already exist 
3. Move back to old multi select style please

2023-10-20 17:04 UTC, akhilmhdh commented on frontend/src/views/SecretMainPage/components/ActionBar/ActionBar.tsx
> +            <div role="button" className="bg-mineshaft-700 hover:bg-mineshaft-500  cursor-pointer flex justify-center items-center border rounded-md border-mineshaft-500 px-[15px] py-1.5 text-gray-20
We have button components please misuse html ones

2023-10-23 21:36 UTC, maidul98 commented on backend/src/controllers/v3/secretsController.ts
> +    const { permission } = await getUserProjectPermissions(req.user._id, workspaceId);
yes we need to check if the user has access to write `from` and `to`

2023-10-23 21:38 UTC, maidul98 commented on backend/src/controllers/v3/secretsController.ts
> +      serviceTokenData: req.authData.authPayload as IServiceTokenData,
Agree, moving secrets should go through approvals if enabled for the environment

2024-02-16 16:31 UTC, maidul98 commented
The backend has moved to Postgres. This PR is now stale.

2024-02-16 16:31 UTC, closed without merging