feat: adds ability to create multiple orgs under the same account
Infisical/infisical pull request #1085
Opened 2023-10-13 05:19 UTC by rtpa25

# Description 📣

Fixes https://github.com/Infisical/infisical/issues/1082
[Screen recording example ](https://www.loom.com/share/328bc13b0cd6429da445a349d766f89d)

## Type ✨

- [ ] Bug fix
- [x] New feature
- [ ] Breaking change
- [ ] Documentation

---

- [x] I have read the [contributing guide](https://infisical.com/docs/contributing/overview), agreed and acknowledged the [code of conduct](https://infisical.com/docs/contributing/code-of-conduct). 📝

2023-10-13 05:37 UTC, rtpa25 commented
@maidul98 @vmatsiiako awaiting review

2023-10-21 09:21 UTC, akhilmhdh requested changes
Rest looks good to me. 

Although one que to @vmatsiiako @maidul98 @dangtony98 

Don't we need some kinda of restriction on number of org created;

2023-10-21 09:21 UTC, akhilmhdh commented on frontend/src/views/Org/components/CreateOrgModal.tsx
> +const schema = yup
Can you please change to zod. We are moving towards `zod` from yup.  As backend also uses zod we wanna keep one validation lib through out infisical

2023-10-21 09:21 UTC, akhilmhdh commented on frontend/src/views/Org/components/CreateOrgModal.tsx
> +          <Button
A cancel button is needed here

2023-10-22 14:52 UTC, maidul98 commented
> Rest looks good to me.

Although one que to @vmatsiiako @maidul98 @dangtony98

Don't we need some kinda of restriction on number of org created;

For time being, I think we can leave it as is. @rtpa25 please address the comments made by Akhi so we can get this merged in

2023-10-22 16:46 UTC, rtpa25 commented
Will do it tom

2023-10-31 05:50 UTC, akhilmhdh approved these changes

2023-10-31 05:51 UTC, merged