Add Secrets Warning Message in Integration Pages (Connect Modal)
Infisical/infisical pull request #1113
Opened 2023-10-23 14:49 UTC by lokesh3097

# Description 📣

Fixes #691

Created a component 'WarningMessage' and used it in all the Integration Pages to provide a warning as mentioned in the issue.

<img width="429" alt="image" src="https://github.com/Infisical/infisical/assets/28948185/bc6e29d1-edbc-42ce-90da-2738fb46b464">

## Type ✨

- [ ] Bug fix
- [ ] New feature
- [ ] Breaking change
- [ ] Documentation
- [x] Minor UX Improvement

# Tests 🛠️
N/A

# Code Snippet
```tsx
const WarningMessage = ({text}: {text: string}): JSX.Element => {
    return (
    <div>
        <div className="flex flex-col bg-mineshaft-800 border border-mineshaft-600 w-full p-4 max-w-lg mt-6 rounded-md">
            <div className="flex flex-row items-center">
                <FontAwesomeIcon icon={faCircleExclamation} className="text-mineshaft-200 text-xl" style={{color: "yellow"}}/>
                <span className="ml-3 text-sm text-mineshaft-100" style={{color: "yellow"}}> {text}
                </span>
            </div>
        </div>
    </div>
    );
}
```

---

- [x] I have read the [contributing guide](https://infisical.com/docs/contributing/overview), agreed and acknowledged the [code of conduct](https://infisical.com/docs/contributing/code-of-conduct). 📝

2023-10-23 16:51 UTC, akhilmhdh requested changes
minor changes.

2023-10-23 16:51 UTC, akhilmhdh commented on frontend/src/pages/integrations/aws-parameter-store/create.tsx
> +import WarningMessage from "../../../components/basic/WarningMessage";
Keep it named export rather than default export

2023-10-23 17:03 UTC, lokesh3097 commented on frontend/src/components/basic/WarningMessage.tsx
> +import { FontAwesomeIcon } from "@fortawesome/react-fontawesome"
> Also why not the new Alert component instead of building from scratch

Are you referring to the one provided in Tailwind?

2023-10-23 17:38 UTC, akhilmhdh commented on frontend/src/components/basic/WarningMessage.tsx
> +import { FontAwesomeIcon } from "@fortawesome/react-fontawesome"
Na I don't think another grouping needed.

And nope the alert component in components v2 folder

2023-10-23 18:01 UTC, lokesh3097 commented on frontend/src/components/basic/WarningMessage.tsx
> +import { FontAwesomeIcon } from "@fortawesome/react-fontawesome"
>And nope the alert component in components v2 folder

Sorry but I cannot see any component with the name 'Alert' under v2 folder? Do you mean any other name?

I have made the mentioned changes.

2023-10-24 13:43 UTC, lokesh3097 commented on frontend/src/components/basic/WarningMessage.tsx
> +import { FontAwesomeIcon } from "@fortawesome/react-fontawesome"
Hi @akhilmhdh! Any other changes to be made?

I see that new integrations (Like Hasura) are being added, which may make these messages stale only to the existing integrations

2023-10-30 18:09 UTC, maidul98 commented
@akhilmhdh please merge it in when you think the PR is ready

2024-02-16 16:38 UTC, maidul98 commented
This will get revamped in integrations v2. Closing out for now

2024-02-16 16:38 UTC, closed without merging