(Fix): Improve reminders
Infisical/infisical pull request #1403
Opened 2024-02-15 00:17 UTC by DanielHougaard

# Description 📣

Prior to this PR, the secret reminders felt a bit half-baked. By half baked I mean that it wasn't possible to update secret reminders without removing and re-creating the reminder, and it wasn't possible to view the existing secret reminder values. This PR fixes both those issues and makes the secret reminders feel more seemless.

- Added functionality for editing existing reminders. 
- Fixed not being able to view existing reminder values. 
- Added reminders to the "More" sidebar drawer.  
- The reminder toolbar now shows "Every X days" instead of "Reminder", when a reminder is enabled for the secret. 

## Type ✨

- [x] Bug fix
- [x] New feature
- [ ] Breaking change
- [ ] Documentation

---

- [x] I have read the [contributing guide](https://infisical.com/docs/contributing/getting-started/overview), agreed and acknowledged the [code of conduct](https://infisical.com/docs/contributing/getting-started/code-of-conduct). 📝

2024-02-15 17:07 UTC, akhilmhdh requested changes
Small change

2024-02-15 17:07 UTC, akhilmhdh commented on frontend/src/views/SecretMainPage/components/SecretListView/SecretItem.tsx
> +    const secretReminderRepeatDays = watch("reminderRepeatDays");
Your already watching for the same prop at top. Can you change this to one watch please

2024-02-15 19:53 UTC, maidul98 approved these changes
Tested it locally, looks good to me. Please do another round of checks in gamma before you merge it in

2024-02-16 16:01 UTC, akhilmhdh approved these changes

2024-02-16 17:00 UTC, merged