Feat integration page
Infisical/infisical pull request #1584
Opened 2024-03-18 11:43 UTC by Salman2301

# Description 📣
This PR add environment, integration and sorting dropdown for the integration page.

## Type ✨

- [ ] Bug fix
- [x] New feature
- [ ] Breaking change
- [ ] Documentation

# Tests 🛠️

https://github.com/Infisical/infisical/assets/40920317/5f15994e-9df5-4f52-ad32-9b4fe948858e

---

- [x] I have read the [contributing guide](https://infisical.com/docs/contributing/getting-started/overview), agreed and acknowledged the [code of conduct](https://infisical.com/docs/contributing/getting-started/code-of-conduct). 📝

2024-03-18 11:56 UTC, Salman2301 commented
I would like to add the integration as an image rather than label. It saves horizontal space that need and aslo looks good imo
<img width="1280" alt="Screenshot 2024-03-18 at 5 25 23 PM" src="https://github.com/Infisical/infisical/assets/40920317/2b4d8136-9da3-46da-86a7-8628b79879ed">

2024-03-18 15:33 UTC, Salman2301 commented
Added tooltip
<img width="1280" alt="Screenshot 2024-03-18 at 8 59 17 PM" src="https://github.com/Infisical/infisical/assets/40920317/297e4f5d-7311-45f6-8176-52478154effc">



We can remove this https://github.com/Infisical/infisical/blob/c91789e6d05cc357b78fa777400e56b058618397/frontend/public/data/frequentConstants.ts#L5

2024-03-18 23:51 UTC, Salman2301 commented
@Grraahaam agree with you on Github icon
Try half the size but it's too feels to small
<img width="1278" alt="Screenshot 2024-03-19 at 5 19 11 AM" src="https://github.com/Infisical/infisical/assets/40920317/9ab72acf-1a25-4bf1-b568-7bd2157f3345">
Try min-8 (32px) looks better
<img width="1278" alt="Screenshot 2024-03-19 at 5 19 26 AM" src="https://github.com/Infisical/infisical/assets/40920317/3c8443cc-1fd1-4d34-9362-ae5a5f7d6dba">

Open to suggestion

2024-03-19 00:00 UTC, Salman2301 commented
With white color
<img width="1278" alt="Screenshot 2024-03-19 at 5 30 44 AM" src="https://github.com/Infisical/infisical/assets/40920317/3993b6f0-be91-473c-9d37-1a055d753f3c">

2024-03-19 17:13 UTC, Salman2301 commented
@akhilmhdh or @maidul98 I want to work on integration logs after this PR... if it's get merged. I would like if anyone take a look.

2024-03-19 17:15 UTC, Salman2301 commented
@Grraahaam Will take a look but it's probably out of scope for this PR. If you can let the team add it somewhere in the project milestone backlog for the light mode. I think that will be the best course of action for now.

2024-03-25 05:57 UTC, akhilmhdh commented
@Salman2301 can you kindly remove the images on left side. It doen't go with the ui at all. Kinda looks bad or mismatching

2024-03-25 06:05 UTC, akhilmhdh requested changes
One more change would be top bar. The select is kinda weird or rather doesn't go with the ui

I would recommend keep the filter and sort as icon buttons to top right. Then  when clicked they could select the various options as needed. 

You can keep the filter like [Radix Menu Edit > Menu](https://www.radix-ui.com/primitives/docs/components/menubar)

2024-03-25 16:46 UTC, Salman2301 commented
@akhilmhdh Do you want the filter and sort to be one icon?
```
Icon click ⌄
 > Filter
     > Development
         > dev
     > Integration
        > ...
 > Sort
     > Sort options 1?
```

---
Or two icons one for filter one for sort?

2024-03-25 16:46 UTC, Salman2301 commented
I use the same ui as the audit log page...

2024-04-11 16:50 UTC, LitoMore commented
Hi, I'm the maintainer of the Simple Icons project.

Please note that the dark mode feature https://cdn.simpleiocns.org/github/black/white won't work in Safari.

See this: https://stackoverflow.com/questions/58493483/issue-with-embedded-svg-images-in-dark-mode

The `<object>` tag may have some security issues, so the better solution would be the `<picture>` tag. Here is an example:

```html
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://cdn.simpleicons.org/github/white">
  <source media="(prefers-color-scheme: light)" srcset="https://cdn.simpleicons.org/github/black">
  <img alt="GitHub" src="https://cdn.simpleicons.org/github/black">
</picture>
```

In the meantime, other CDN services exist, such as jsDelivr and unpkg. Here are their differences:

### cdn.simpleicons.org

It supports brand colors and SVG inline color schemes for dark mode. This service is hosted on Vercel. It does not support history versions. It always provides the latest version of Simple Icons. Which means an icon is subject to removal. See [removal of brands](https://github.com/simple-icons/simple-icons/blob/develop/DISCLAIMER.md#removal-of-brands).

### jsDelivr & unpkg

It's more professional for CDN, and it has a faster response speed. It supports history versions. But it does not have a fill color. The color is up to your HTML context.

**Note:** jsDelivr has `Access-Control-Allow-Origin: *` support, but unpkg does not. This means you cannot use the unpkg resource in CSS `background: url(...)`.

## Which solution would be better?

It depends on what you need about the image/icon.

### If you only need black and white

The jsDelivr would be the best solution. You can use CSS `invert()` to get black and white from a single resource.

### If you want the brand color

#### jsDelivr

You could bundle the [simple-icons.json](https://github.com/simple-icons/simple-icons/blob/develop/_data/simple-icons.json) file only. It has the full icon list with its slug and brand color value. And use [CSS mask](https://developer.mozilla.org/en-US/docs/Web/CSS/mask) to apply the brand color to your jsDelivr resource. Here is an example: https://github.com/LitoMore/simple-icons-figma/blob/a5c2fae7ddcb68985c54d7ac7a0f3a9c75cca34f/source/components/icon.tsx#L62-L68.

#### cdn.simpleicons.org

This is convenient but has a slower response than jsDelivr. And it has some limitations:

Consuming the Vercel resource of [LitoMore/simple-icons-cdn](https://github.com/LitoMore/simple-icons-cdn) rapidly may quickly reach the rate limit. We're using the Vercel free plan, so this solution is not friendly to some services with a large request volume.

---

Feel free to ping me if you have any questions.

2024-05-07 16:31 UTC, maidul98 commented
I think this is useful feature as users sometimes have 100s of integrations. One feedback, i think the two filters being visible from the start makes it look like a lot is going on. It would be best if the user can click some filter icon and then they see those options. By default the filters should also be set to defaults such as `all integrations` and `all environments`. After this, i think we can merge this in. Does this make sense? 
<img width="518" alt="Screenshot 2024-05-07 at 12 27 51 PM" src="https://github.com/Infisical/infisical/assets/9300960/ce33530d-13af-4189-8ec7-6ef6c0a0473f">

2025-02-13 00:04 UTC, maidul98 commented
Intgerations v2 has been rolled out by the Infisical team

2025-02-13 00:04 UTC, closed without merging