Add ability to use existing postgres server with infisical-standalone helm chart. Fixes #1765
Infisical/infisical pull request #1766
Opened 2024-04-30 12:38 UTC by mpsOxygen

# Description 📣

This adds the option to use a existing Postgres instance with the infisical-standalone helm chart. It uses an existing secret to get the database connection URI.

## Type ✨

- [ ] Bug fix
- [x]  New feature
- [ ] Breaking change
- [ ] Documentation

# Tests 🛠️

I set the values and run helm template .

---

- [x] I have read the [contributing guide](https://infisical.com/docs/contributing/getting-started/overview), agreed and acknowledged the [code of conduct](https://infisical.com/docs/contributing/getting-started/code-of-conduct). 📝

2024-05-02 12:00 UTC, mpsOxygen commented
While waiting for this to be approved I also tested this in my production environment. Works as intended.

2024-05-02 15:35 UTC, maidul98 commented
Hey @mpsOxygen, you should already be able to do this when you disable the in cluster Postgres and set your own postgres connection URL via `DB_CONNECTION_URI`. An example is shown in step 4 here https://infisical.com/docs/self-hosting/deployment-options/kubernetes-helm. Is this helpful?

2024-05-02 16:04 UTC, mpsOxygen commented
Hello @maidul98,

I know about kubeSecretRef: "infisical-secrets", but I now realize I did not explain my use case correctly.  

I use an operator to take care of postgres. When it spins up a postgres cluster for me, it creates a secret with all needed information (db name, user, pass, uri, etc). The password for example is randomly generated each time a cluster is spun up. Or it maybe even changes. The operator takes care of everything and puts it in a secret it creates. All I need from my apps is to say: get your  DB_CONNECTION_URI from the secret the operator created. So while I know about the secret that gives infisical it's ENVs, using it would mean to manually update it every time something changes. This patch fixes my problem because I just tell infisical the name of the secret the postgres operator uses to keep postgres connection info.

2024-05-29 11:10 UTC, mpsOxygen commented
Any updates on this? I am willing to make any changes necessary to the code to get it merged.

2024-06-03 11:32 UTC, WladyX commented
I'm also using cnpg postgres and would like to see this one merged.

2024-07-03 07:49 UTC, mpsOxygen commented
Any updates on this? I am willing to make any changes necessary to the code to get it merged.

2024-07-04 15:39 UTC, maidul98 requested changes
Thanks for the PR, i understand your usecase. Currently, we have:

```
{{- if .Values.postgresql.enabled }}
        - name: DB_CONNECTION_URI
          value: {{ include "infisical.postgresDBConnectionString" . }}
{{- end }}
```

I think what might make it user for the rest of the user is if we instead have the default connection URL be from {{ include "infisical.postgresDBConnectionString" . }} or user defined one. User defined one can be from the infisical-secret if defined or from the custom one you are adding here. 

Does this make sense? If so, can you please make these changes? Thanks

2024-07-05 13:05 UTC, mpsOxygen commented
It's not clear exactly what changes you want. The current PR leaves current functionality untouched, it just adds an option to enable defining a preexisting secret with the connection string. Could you be more specific please?

2024-09-05 00:40 UTC, davidshare commented
I see what you are pointing out @mpsOxygen - I am facing the same issues with the chart. In my case, I still want to use the postgres server provided in the charts, but I do not want to expose my secrets in a values file. Which should leave me with an option to pass an existing secret.

2024-09-05 09:14 UTC, mpsOxygen commented
@davidshare You could just use the bitami Postgres chart functionality for that: https://artifacthub.io/packages/helm/bitnami/postgresql?modal=values

The path is: global.auth.existingSecret

2024-09-06 21:18 UTC, cook1emr commented
@mpsOxygen have you had clarity from @maidul98 ? I would love to see this merged to use easily with cnpg

2024-09-09 07:14 UTC, mpsOxygen commented
@cook1emr unfortunately no.

2024-09-28 20:00 UTC, fcornelius commented
+1 for this to use it with CNPG postgres

2024-10-11 02:18 UTC, maidul98 commented
Support for this has been added here to the latest release https://github.com/Infisical/infisical/blob/main/helm-charts/infisical-standalone-postgres/values.yaml#L59

2024-10-11 02:18 UTC, closed without merging