feat: Infisical Binary
Infisical/infisical pull request #2041
Opened 2024-06-28 19:00 UTC by DanielHougaard

# Description 📣

As per requested by users, we now support running Infisical as a standalone binary. Previously it wasn't possible to deploy Infisical anywhere without Docker and various build-steps, increasing the self-hosting complexity. With the binary, all the user needs to do is:

1. Set environment variables
2. Run the binary file (./binary-file)

This is achieved through the use of [vercel/pkg](https://github.com/vercel/pkg). One trade off however is that vercel/pkg doesn't support ESM. So we need to convert our ESM code to CJS. This is handled as a part of the build step. This however means that I also had to downgrade two of our internal packages (nanoid and slugify), as the newer versions are pure ESM.

## Type ✨

- [ ] Bug fix
- [x] New feature
- [ ] Breaking change
- [ ] Documentation

---

- [x] I have read the [contributing guide](https://infisical.com/docs/contributing/getting-started/overview), agreed and acknowledged the [code of conduct](https://infisical.com/docs/contributing/getting-started/code-of-conduct). 📝

2024-07-03 02:24 UTC, maidul98 submitted a review, later dismissed
lgtm, i think there is a package lock conflict. otherwise good to go

2024-07-03 02:24 UTC, maidul98 commented on .github/workflows/build-binaries.yml
> +                  node-version: 18
Should we now set this to version 20?

2024-07-03 06:14 UTC, akhilmhdh requested changes
please change action to node 20.

Rest everything looks all good

2024-07-05 01:16 UTC, maidul98 approved these changes
lgtm

2024-07-05 01:16 UTC, maidul98 commented on .github/workflows/build-binaries.yml
> +                      target: node18-linux
18 or 20 here?

2024-07-05 23:42 UTC, maidul98 approved these changes
lgtm!

2024-07-05 23:43 UTC, merged

2024-07-12 07:18 UTC, vhsantos commented
Hi,

Do you have any estimate when the binaries will be available ?? 
Thanks in advance.

2024-07-16 03:51 UTC, DanielHougaard commented
Hi @vhsantos,

I'm finishing up the deployment and documentation for the binaries. Currently only Debian/Ubuntu is supported. Which system are you looking to use the binaries on?

2024-07-16 07:21 UTC, vhsantos commented
Hi @DanielHougaard 

Actually I'm looking for RHEL/AlmaLinux 9.
Maybe if you share with me the deployment/documentation I can help with something (init scripts, testing, etc) on RHEL ??

2024-07-16 14:47 UTC, DanielHougaard commented
Hi @vhsantos,

The only thing that I see as a concern for RHEL, is [yao-pkg/pkg](https://github.com/yao-pkg/pkg)'s ability to package to that distro. If we're able to package nodejs to the RHEL distro, then it's very straight forward from there!