feat: allow access approvals with user groups
Infisical/infisical pull request #2458
Opened 2024-09-19 19:58 UTC by meetcshah19

# Description 📣
Allow secret access approvals using user groups.
Demo : https://github.com/user-attachments/assets/4f839d1f-8442-4da6-9163-a91866fbdba6

## Type ✨

- [ ] Bug fix
- [ ] New feature
- [ ] Breaking change
- [ ] Documentation

- [ ] I have read the [contributing guide](https://infisical.com/docs/contributing/getting-started/overview), agreed and acknowledged the [code of conduct](https://infisical.com/docs/contributing/getting-started/code-of-conduct). 📝

2024-09-20 14:03 UTC, DanielHougaard requested changes

2024-09-20 21:06 UTC, maidul98 commented on backend/src/ee/services/access-approval-policy/access-approval-policy-service.ts
> +      usersPromises.push(groupDAL.findAllGroupMembers({ orgId: actorOrgId, groupId, offset: 0 }));
Might be best to keep as is for readability purposes

2024-09-23 12:35 UTC, DanielHougaard requested changes
Looks good! I left a few comments

2024-09-23 12:35 UTC, DanielHougaard commented on backend/src/ee/routes/v1/access-approval-policy-router.ts
> +          .min(1),
Same as above

2024-09-23 12:35 UTC, DanielHougaard commented on backend/src/ee/routes/v1/access-approval-policy-router.ts
> +          .min(1),
I would add a custom message on the approvers array.

I forget the exact syntax, but I think it's just a separate parameter like so: `.min(1, { message: "At least one approver should be provided" } )`

2024-09-23 12:35 UTC, DanielHougaard commented on backend/src/ee/routes/v1/secret-approval-policy-router.ts
> +          .array()
Same as above

2024-09-23 12:35 UTC, DanielHougaard commented on backend/src/ee/routes/v1/secret-approval-policy-router.ts
> +        approvers: z
Same as above

2024-09-23 12:35 UTC, DanielHougaard commented on backend/src/ee/services/access-approval-policy/access-approval-policy-dal.ts
> +              type: "group"
Please use the `ApproverType` enum here

2024-09-23 12:35 UTC, DanielHougaard commented on backend/src/ee/services/secret-approval-request/secret-approval-request-service.ts
> +        approverId ? reviewers[approverId.toString()] === ApprovalStatus.APPROVED : null
Nit: Would be more clear if you change `null` to `false`

2024-09-23 12:35 UTC, DanielHougaard commented on backend/src/ee/services/secret-approval-request/secret-approval-request-service.ts
> +        approverId ? reviewers[approverId.toString()] === ApprovalStatus.APPROVED : null
Why are we doing approverId.toString() when we are already checking if it's defined, by using the ternary operator?

2024-09-23 13:39 UTC, DanielHougaard approved these changes
lgtm, good work!

2024-09-23 13:44 UTC, merged