feat: allow users to replace auth methods
Infisical/infisical pull request #2477
Opened 2024-09-24 15:38 UTC by meetcshah19

# Description 📣
Allow users to replace / overwrite auth methods for identities.

## Type ✨

- [ ] Bug fix
- [ ] New feature
- [ ] Breaking change
- [ ] Documentation

---

- [ ] I have read the [contributing guide](https://infisical.com/docs/contributing/getting-started/overview), agreed and acknowledged the [code of conduct](https://infisical.com/docs/contributing/getting-started/code-of-conduct). 📝

2024-09-24 17:54 UTC, dangtony98 commented
Note: Instead of passing `initialAuthMethod` prop into each Form component, you can also get the it through `useGetIdentityById` in the form to get the auth method since it is specified on the identity.

I do think that this PR may conflict with the initiative to add multiple auth methods per identity @DanielHougaard

2024-09-24 18:05 UTC, DanielHougaard commented
We're leaving this PR as-is for now because we have another initiative that will take precedence over this.

2024-09-30 22:35 UTC, scott-ray-wilson requested changes

2024-09-30 22:35 UTC, scott-ray-wilson commented on frontend/src/views/Org/MembersPage/components/OrgIdentityTab/components/IdentitySection/IdentityAuthMethodModal.tsx
When you open this modal, change the selected auth method and close it again, and re-open it, it doesn't reset back to the currently used auth method, I think this should reset on close

2024-09-30 22:55 UTC, scott-ray-wilson requested changes

2024-09-30 22:55 UTC, scott-ray-wilson commented on frontend/src/views/Org/MembersPage/components/OrgIdentityTab/components/IdentitySection/IdentityAuthMethodModal.tsx
Also seems like the general logic of this whole flow isn't working?

<img width="1728" alt="image" src="https://github.com/user-attachments/assets/b7c6da85-a76c-4578-bb62-ca188a5fd1c0">

2024-09-30 23:20 UTC, scott-ray-wilson commented on frontend/src/views/Org/MembersPage/components/OrgIdentityTab/components/IdentitySection/IdentityAuthMethodModal.tsx
@meetcshah19 this error was due to having the confirm overwrite modal inside the form, the button click on the form triggered the submit on the form as well

2024-10-01 00:04 UTC, scott-ray-wilson approved these changes

2024-10-01 03:37 UTC, maidul98 approved these changes
tested it out, works as expected scott and meet

2024-10-01 03:38 UTC, merged