WIP feat: github integration with Github app auth
Infisical/infisical pull request #2566
Opened 2024-10-09 19:23 UTC by sheensantoscapadngan

# Description 📣

## Type ✨

- [ ] Bug fix
- [ ] New feature
- [ ] Improvement
- [ ] Breaking change
- [ ] Documentation

# Tests 🛠️

```sh
# Here's some code block to paste some code snippets
```

---

- [ ] I have read the [contributing guide](https://infisical.com/docs/contributing/getting-started/overview), agreed and acknowledged the [code of conduct](https://infisical.com/docs/contributing/getting-started/code-of-conduct). 📝

2024-10-15 21:10 UTC, scott-ray-wilson requested changes
Looking good other than a few things pointed out below. Using previous OAuth version of GitHub integration also worked as expected

2024-10-15 21:10 UTC, scott-ray-wilson commented on docs/integrations/cicd/githubactions.mdx
nit: references to `Github` that should be `GitHub`

2024-10-15 21:10 UTC, scott-ray-wilson commented on frontend/src/pages/integrations/github/auth-mode-selection.tsx
> +        <title>Select Github Integration Auth</title>
nit: should be `GitHub`

2024-10-15 21:10 UTC, scott-ray-wilson commented on frontend/src/pages/integrations/github/auth-mode-selection.tsx
> +            <span className="ml-2.5">Github Integration </span>
nit: should be `GitHub`

2024-10-15 21:10 UTC, scott-ray-wilson commented on frontend/src/pages/integrations/github/auth-mode-selection.tsx
> +              <SelectItem value={AuthMethod.APP}>Github App (Recommended)</SelectItem>
nit: should be `GitHub`

2024-10-15 21:10 UTC, scott-ray-wilson commented on frontend/src/pages/integrations/github/auth-mode-selection.tsx
> +              Connect to Github
nit: should be `GitHub`

2024-10-16 11:28 UTC, sheensantoscapadngan commented on backend/src/services/integration-auth/integration-sync-secret.ts
oh nice catch! I've updated the self-hosted docs to include the missing repository permission: Environments

<img width="740" alt="image" src="https://github.com/user-attachments/assets/a78f1bc1-d9de-4c6a-9482-8003de329ea7">

2024-10-16 11:29 UTC, sheensantoscapadngan commented on frontend/src/pages/integrations/github/auth-mode-selection.tsx
To test it with Github app, you will need to use a connection where the Github app is installed to an organization

2024-10-16 11:30 UTC, sheensantoscapadngan commented on backend/src/services/integration/integration-service.ts
> +    const deletedIntegration = await integrationDAL.deleteById(id);
this affects other integrations as well... basically we won't be deleting the integrationAuth anymore unless it's explicitly revoked

2024-10-16 11:41 UTC, sheensantoscapadngan commented on frontend/src/pages/integrations/select-integration-auth.tsx
I see. I updated the label to be clearer. Does this help? 
<img width="1512" alt="image" src="https://github.com/user-attachments/assets/22434d4b-2266-4827-a425-68edc08d6589">

2024-10-16 17:52 UTC, scott-ray-wilson approved these changes

2024-10-16 18:02 UTC, merged