fix: form not submitting on keyboard enter
Infisical/infisical pull request #851
Opened 2023-08-12 19:28 UTC by sreehari2003

# Description 📣

- closes #850 

## Type ✨

- [x] Bug fix
- [ ] New feature
- [ ] Breaking change
- [ ] Documentation

# Tests 🛠️
 I did some manual testing and it is working ok
```sh
  https://app.infisical.com/login/sso?token=randomnumber

```
 is breaking your client  side , I think it should be fixed
---

- [x] I have read the [contributing guide](https://infisical.com/docs/contributing/overview), agreed and acknowledged the [code of conduct](https://infisical.com/docs/contributing/code-of-conduct). 📝

2023-08-13 06:12 UTC, akhilmhdh requested changes

2023-08-13 06:12 UTC, akhilmhdh commented on frontend/src/views/Login/components/PasswordStep/PasswordStep.tsx
>                      onClick={async () => handleLogin()}
Can you please move this onClick to onSubmit in the form component. because this is not a good pattern to put both submit and onClick here

2023-08-13 06:12 UTC, akhilmhdh commented on frontend/src/views/Login/components/SAMLSSOStep/SAMLSSOStep.tsx
>                      onClick={() => {
Same goes here

2023-08-13 08:32 UTC, sreehari2003 commented on frontend/src/views/Login/components/SAMLSSOStep/SAMLSSOStep.tsx
>                      onClick={() => {
done

2023-08-14 05:24 UTC, akhilmhdh approved these changes

2023-08-21 19:53 UTC, merged